// <auto-generated />
using System;
using DevSkill.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSkill.Inventory.Web.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20241022163946_UpdateProductTable")]
    partial class UpdateProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicableTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90a51ecd-95f4-4e92-9efb-09b31a1109a4"),
                            ApplicableTaxName = "Food"
                        },
                        new
                        {
                            Id = new Guid("911cdef1-6ed6-4350-a917-380cf91db201"),
                            ApplicableTaxName = "Sales Tax"
                        },
                        new
                        {
                            Id = new Guid("7226f718-2d19-4fb2-9bee-586281257df4"),
                            ApplicableTaxName = "Fruits"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BarcodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BarcodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29b75b7c-5fd8-44c5-9145-a8b2ee554c69"),
                            BarcodeTypeName = "QR Code"
                        },
                        new
                        {
                            Id = new Guid("8e57fb64-edd0-46d1-822e-23a9c4c43007"),
                            BarcodeTypeName = "UPC"
                        },
                        new
                        {
                            Id = new Guid("79aecfcf-1f84-4a3d-a8c7-83ad6fd71915"),
                            BarcodeTypeName = "NFC"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8ee098-f7ba-496c-94b9-b89527289150"),
                            BandOrigin = "",
                            BrandName = "Apple",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("04a402d6-9b94-4abb-b4cd-572c5980ad5c"),
                            BandOrigin = "",
                            BrandName = "Samsung",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("a3e7eae3-7119-47d6-9929-1d161cb936b0"),
                            BandOrigin = "",
                            BrandName = "Sony",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1205f00-10f0-470c-b8bb-afdb8752846a"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse A",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("e0d5f778-e519-461d-af18-828444fc9383"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse B",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("4faa4a52-6b9a-4e16-aeea-eca6f6415cf5"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Downtown Store",
                            State = "",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c6bde57-245f-4b6d-9322-6aa392766714"),
                            CategoryCode = "",
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("5d2c6a3e-d22f-4997-a11c-0c224331f8fa"),
                            CategoryCode = "",
                            CategoryName = "Home Appliances",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("19753583-7641-4763-ae49-bfb725bb22ab"),
                            CategoryCode = "",
                            CategoryName = "Clothing",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicableTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarcodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExciseTax")
                        .HasColumnType("float");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InclusiveTax")
                        .HasColumnType("float");

                    b.Property<double>("MarginTax")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("SellingPriceTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoreTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicableTaxId");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellingPriceTaxId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a04f119-b91c-46d7-966a-7139d497810a"),
                            ProductTypeName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("c9980811-73e1-4869-b942-e66ec16bf0fc"),
                            ProductTypeName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("0868600f-12e7-4fac-80bd-25000c73fc6c"),
                            ProductTypeName = "Food"
                        },
                        new
                        {
                            Id = new Guid("9a83f754-7410-4248-ad5d-ef75ca92d5f6"),
                            ProductTypeName = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("37f52d88-0f86-4a92-a84d-13e0777d496a"),
                            ProductTypeName = "Toys"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SellingPriceTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SellingPriceTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SellingPriceTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("526b2298-ecac-432c-bcc8-896da6df4826"),
                            SellingPriceTaxName = "Exclusive"
                        },
                        new
                        {
                            Id = new Guid("cb30dd16-06f0-457a-b536-bad78a04ca0a"),
                            SellingPriceTaxName = "Inclusive"
                        },
                        new
                        {
                            Id = new Guid("78910528-3642-41af-96e3-87c96028e905"),
                            SellingPriceTaxName = "Zero Rate"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("725273db-f0a2-468e-af8b-6d8fe208d283"),
                            SubcategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("b73a6fe3-dc27-4b00-8f80-af1960f9e6c6"),
                            SubcategoryName = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("40fce42a-91a9-4975-85dc-6bde96d7ac49"),
                            SubcategoryName = "Televisions"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowDecimal")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba7b41ea-d486-4052-a9fa-74b105e179d1"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("75e260e7-26c7-43c1-a091-dcd5a1b6a457"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("8b2267d3-c73f-4084-8f12-841d911628ba"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Piece"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d04851da-eed6-4676-a187-2ccc43b14a28"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "1 Year"
                        },
                        new
                        {
                            Id = new Guid("dd0e8aa6-7e8c-40d5-a995-774b866c4f6a"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("a91af553-7cd7-4864-ad95-ed054af0ed6d"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "3 Years"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.ApplicableTax", "ApplicableTax")
                        .WithMany()
                        .HasForeignKey("ApplicableTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BarcodeType", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SellingPriceTax", "SellingPriceTax")
                        .WithMany()
                        .HasForeignKey("SellingPriceTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicableTax");

                    b.Navigation("BarcodeType");

                    b.Navigation("Brand");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Category");

                    b.Navigation("ProductType");

                    b.Navigation("SellingPriceTax");

                    b.Navigation("Subcategory");

                    b.Navigation("Unit");

                    b.Navigation("Warranty");
                });
#pragma warning restore 612, 618
        }
    }
}
