// <auto-generated />
using System;
using DevSkill.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSkill.Inventory.Web.Migrations.InventoryDb
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20241027180249_UpdateStockAdjustment2")]
    partial class UpdateStockAdjustment2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicableTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09307dd9-7f42-4353-a4a7-3e8db0b2d024"),
                            ApplicableTaxName = "Food"
                        },
                        new
                        {
                            Id = new Guid("231e22bd-c47b-411d-8723-d7f310d92599"),
                            ApplicableTaxName = "Sales Tax"
                        },
                        new
                        {
                            Id = new Guid("5074ea0c-3e41-4252-9196-89d117c1f0dc"),
                            ApplicableTaxName = "Fruits"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BarcodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BarcodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6efb2c8-ee49-4b6b-acd5-563b841a932c"),
                            BarcodeTypeName = "QR Code"
                        },
                        new
                        {
                            Id = new Guid("46ed0d78-088a-419e-91b9-f94d99255021"),
                            BarcodeTypeName = "UPC"
                        },
                        new
                        {
                            Id = new Guid("8d388b79-3bc1-41a4-8e61-0fdb85c9427f"),
                            BarcodeTypeName = "NFC"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ba16274-7018-4be5-adb9-bdd7ac66082c"),
                            BandOrigin = "",
                            BrandName = "Apple",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("a3b37722-b7f2-4f66-9ec3-7c07e80bbb85"),
                            BandOrigin = "",
                            BrandName = "Samsung",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("601fd9c7-7569-4b8a-9ef6-88c33f2d2a6d"),
                            BandOrigin = "",
                            BrandName = "Sony",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5b137dd-d3f4-4e68-bbbb-c802f5ac25be"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse A",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("dd18b58e-ce05-48d7-99ed-3afad023141e"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse B",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("5df26722-63d8-4b15-aa6a-e0a1924cf75c"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Downtown Store",
                            State = "",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aba5b3ae-5ba0-4e01-9e09-6b7f28973e37"),
                            CategoryCode = "",
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("753f76f1-98bf-4c47-bdfc-2868fac8ca3a"),
                            CategoryCode = "",
                            CategoryName = "Home Appliances",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("f05a076e-377d-4cf7-a149-ccb96cc4e43c"),
                            CategoryCode = "",
                            CategoryName = "Clothing",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApplicableTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarcodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExciseTax")
                        .HasColumnType("float");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InclusiveTax")
                        .HasColumnType("float");

                    b.Property<double>("MarginTax")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("SellingPriceTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoreTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicableTaxId");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellingPriceTaxId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da7602fd-a642-4de3-9763-031784116a1e"),
                            ProductTypeName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("34123722-096c-42cf-8742-e9a80682cb8c"),
                            ProductTypeName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("4888284c-1458-4909-99d8-64981174ce8e"),
                            ProductTypeName = "Food"
                        },
                        new
                        {
                            Id = new Guid("6f3c913c-753e-4e8e-9a91-4c3d3d6880a8"),
                            ProductTypeName = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("80066a04-a1ee-427f-9df5-da47705b7da5"),
                            ProductTypeName = "Toys"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SellingPriceTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SellingPriceTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SellingPriceTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbd0c99e-5f01-4b43-b3f4-2caef913c165"),
                            SellingPriceTaxName = "Exclusive"
                        },
                        new
                        {
                            Id = new Guid("ba2ea601-45a8-4488-936f-f1afa3286f88"),
                            SellingPriceTaxName = "Inclusive"
                        },
                        new
                        {
                            Id = new Guid("6e94f51a-6574-4671-9cd8-1696213cd0ef"),
                            SellingPriceTaxName = "Zero Rate"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdjustmentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebf2ec90-3724-4018-b3e0-70cf09fda857"),
                            AdjustmentTypeName = "Normal",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("cd66911e-1e6e-4cc4-82dd-c84bc1461816"),
                            AdjustmentTypeName = "Abnormal",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdjustmentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("AdjustmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmountRecover")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12a9f322-b263-4d17-81ee-56c4201c4d21"),
                            SubcategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("95f4d772-1c91-4c07-ba32-551180083070"),
                            SubcategoryName = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("123a49b7-64d1-45c9-8553-52535d9360e0"),
                            SubcategoryName = "Televisions"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowDecimal")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df9123bf-c00c-426c-9e5b-26e47c864dc2"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("f2015fae-b2cb-4beb-a593-6d0b1725f45a"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("39ae2860-10cf-47d9-a8d2-6b9dec9d9222"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Piece"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78b258a8-8155-4f1c-9e81-0c4af2b130ce"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "1 Year"
                        },
                        new
                        {
                            Id = new Guid("aba2a488-ecff-406f-be3b-efd030055afc"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("d119e8e8-c41c-4e7c-89a8-42e39a85a4ed"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "3 Years"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.ApplicableTax", "ApplicableTax")
                        .WithMany()
                        .HasForeignKey("ApplicableTaxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BarcodeType", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SellingPriceTax", "SellingPriceTax")
                        .WithMany()
                        .HasForeignKey("SellingPriceTaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicableTax");

                    b.Navigation("BarcodeType");

                    b.Navigation("Brand");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Category");

                    b.Navigation("ProductType");

                    b.Navigation("SellingPriceTax");

                    b.Navigation("Subcategory");

                    b.Navigation("Unit");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", "AdjustmentType")
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustmentType");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
