// <auto-generated />
using System;
using DevSkill.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSkill.Inventory.Web.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20241025032253_InventoryAllTable")]
    partial class InventoryAllTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicableTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c264b3f9-7a62-4ebd-9ef0-1cf1541cf8c4"),
                            ApplicableTaxName = "Food"
                        },
                        new
                        {
                            Id = new Guid("cf90a96a-5386-4dd0-b297-79a4b038c652"),
                            ApplicableTaxName = "Sales Tax"
                        },
                        new
                        {
                            Id = new Guid("c6b5273b-9892-49d5-96c2-1b551c884934"),
                            ApplicableTaxName = "Fruits"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BarcodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BarcodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a021909-9ae8-42c8-8fe7-e67e02940999"),
                            BarcodeTypeName = "QR Code"
                        },
                        new
                        {
                            Id = new Guid("28628019-c539-484f-8641-ae9e0f2dd888"),
                            BarcodeTypeName = "UPC"
                        },
                        new
                        {
                            Id = new Guid("b848c430-96f5-4bd2-877a-8f5b6e7cc3fa"),
                            BarcodeTypeName = "NFC"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e995cab2-bd88-4597-ae01-31a713e2c2af"),
                            BandOrigin = "",
                            BrandName = "Apple",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("3144a24a-9871-4d36-87ec-594304dfc5a5"),
                            BandOrigin = "",
                            BrandName = "Samsung",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("5f6d7589-ebe2-4172-8bd2-a01ac423f933"),
                            BandOrigin = "",
                            BrandName = "Sony",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a53bdd-304f-4e75-ba96-483a6a7fa68e"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse A",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("3da84706-747f-4b61-9a91-92e1b45e9202"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse B",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("8283ddb8-e5c6-4b8a-9899-c7960d6e792b"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Downtown Store",
                            State = "",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17a9d308-d905-4e51-abaf-d5af1deb7968"),
                            CategoryCode = "",
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("e4503a07-4e9f-4ae1-a9cc-707f6dd029c6"),
                            CategoryCode = "",
                            CategoryName = "Home Appliances",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("a8a93ef7-e00d-4e03-803b-a15687db8d08"),
                            CategoryCode = "",
                            CategoryName = "Clothing",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicableTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarcodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExciseTax")
                        .HasColumnType("float");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InclusiveTax")
                        .HasColumnType("float");

                    b.Property<double>("MarginTax")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("SellingPriceTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoreTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicableTaxId");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellingPriceTaxId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bf35d50-ddc1-401b-9663-247f16969897"),
                            ProductTypeName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("86a77b47-35ff-457b-80f6-92723487effa"),
                            ProductTypeName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("8915f6f3-345b-427b-aeee-8f3f5f527aa1"),
                            ProductTypeName = "Food"
                        },
                        new
                        {
                            Id = new Guid("48e71b16-8973-4a47-acc9-b56174c5b474"),
                            ProductTypeName = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("e1609561-adcb-4fa4-9f42-8f3f8f09b08c"),
                            ProductTypeName = "Toys"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SellingPriceTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SellingPriceTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SellingPriceTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43e09a64-f917-40df-abec-3b8315101fbd"),
                            SellingPriceTaxName = "Exclusive"
                        },
                        new
                        {
                            Id = new Guid("d531544d-af73-4e96-8b81-ca96f1af8811"),
                            SellingPriceTaxName = "Inclusive"
                        },
                        new
                        {
                            Id = new Guid("24835120-9ab3-4156-b139-dc6d4c47e8cb"),
                            SellingPriceTaxName = "Zero Rate"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdjustmentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019d9193-08d7-434a-8ac4-c5af7eb58a00"),
                            AdjustmentTypeName = "Normal",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("fbefbd69-6b34-40e8-a23a-9aac1904d70d"),
                            AdjustmentTypeName = "Abnormal",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AdjustmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmountRecover")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0bd1ed4-09af-47b2-900e-3850682f8365"),
                            SubcategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("4c9e0bf1-39f8-4e24-bc84-02eb0e06299d"),
                            SubcategoryName = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("482f7c94-0a89-41f1-8328-d15f9858d1c4"),
                            SubcategoryName = "Televisions"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowDecimal")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01f4bd14-cd2a-44b8-8af2-1022a671c9c7"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("4fcaf20e-4753-4b91-93d5-c52b7f510b1b"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("c594b92f-38ab-42b5-bedc-814a51ea5aad"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Piece"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d525efd7-0fdd-4142-8b6d-f6a5ce1fc75a"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "1 Year"
                        },
                        new
                        {
                            Id = new Guid("bed9bf32-e1ba-4b97-b88b-78bcd3aa127e"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("3071b0d8-6904-4763-8a01-96ccce260ad3"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "3 Years"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.ApplicableTax", "ApplicableTax")
                        .WithMany()
                        .HasForeignKey("ApplicableTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BarcodeType", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SellingPriceTax", "SellingPriceTax")
                        .WithMany()
                        .HasForeignKey("SellingPriceTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicableTax");

                    b.Navigation("BarcodeType");

                    b.Navigation("Brand");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Category");

                    b.Navigation("ProductType");

                    b.Navigation("SellingPriceTax");

                    b.Navigation("SubCategory");

                    b.Navigation("Unit");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", "AdjustmentType")
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustmentType");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
