// <auto-generated />
using System;
using DevSkill.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSkill.Inventory.Web.Migrations.InventoryDb
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260621165051_stockTransfer2")]
    partial class stockTransfer2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ApplicableTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("074a518f-6579-428b-9b28-420735e603cf"),
                            ApplicableTaxName = "Food",
                            Description = "",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("65bec287-491e-4049-913b-9f89a6902477"),
                            ApplicableTaxName = "Sales Tax",
                            Description = "",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("51b67a8a-2145-4510-8449-07aabdcbe6d9"),
                            ApplicableTaxName = "Fruits",
                            Description = "",
                            TaxRate = 0m
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BarcodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BarcodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa022281-d204-4576-bdaa-8620c52b6f60"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "QR Code"
                        },
                        new
                        {
                            Id = new Guid("60f1519a-0abd-462e-adf6-03adf4246aa8"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "UPC"
                        },
                        new
                        {
                            Id = new Guid("1105b21b-5d98-41a5-a5af-ab2ef3ee9812"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "NFC"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08a94d1a-e513-44f4-af63-920de1946599"),
                            BandOrigin = "",
                            BrandName = "Apple",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("ae29428a-2664-4965-8f7a-02c213e39a94"),
                            BandOrigin = "",
                            BrandName = "Samsung",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("d0688470-aabc-41d7-a41e-281ca55a9c9a"),
                            BandOrigin = "",
                            BrandName = "Sony",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eaabb893-8ab6-4209-9668-8671d245fd78"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse A",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("405624dc-eafa-4d2f-bca9-35f42f7c3a9c"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Warehouse B",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("363f9a86-a5da-4d06-a988-5480bf6c9ccf"),
                            Address = "",
                            City = "",
                            Country = "",
                            LocationName = "Downtown Store",
                            State = "",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4850b835-1630-4294-bd9d-217f3d04e8c3"),
                            CategoryCode = "",
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("50d6edae-0c51-4748-af99-683bd0bf061e"),
                            CategoryCode = "",
                            CategoryName = "Home Appliances",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("d7256850-fae9-43a1-8880-bbf10c44c859"),
                            CategoryCode = "",
                            CategoryName = "Clothing",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApplicableTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarcodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExciseTax")
                        .HasColumnType("float");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InclusiveTax")
                        .HasColumnType("float");

                    b.Property<double>("MarginTax")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("SellingPriceTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoreTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicableTaxId");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellingPriceTaxId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9910dd4-edd9-4441-aa97-4b68bfc5265d"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("ad117cc3-fc4b-48ab-b698-216d9b2ffe64"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("85e924d8-77d6-41b3-be6a-b4e5960c343d"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Food"
                        },
                        new
                        {
                            Id = new Guid("161821a0-b62b-487d-b314-7cee51d828df"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("00e331b0-8aa1-41ab-a503-fa681c74667f"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Toys"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SellingPriceTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellingPriceTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SellingPriceTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b86d9049-2d05-426a-abec-42b88d88a731"),
                            Description = "",
                            SellingPriceTaxName = "Exclusive",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("d7deb087-0936-4a2f-a11a-6b4c8553141e"),
                            Description = "",
                            SellingPriceTaxName = "Inclusive",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("e1907d5c-60d1-420b-9e1a-901ad0b03313"),
                            Description = "",
                            SellingPriceTaxName = "Zero Rate",
                            TaxRate = 0m
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sign")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdjustmentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4095c4aa-0f0c-406c-9c68-7cf54123b628"),
                            AdjustmentTypeName = "Normal",
                            Description = "",
                            Sign = 0
                        },
                        new
                        {
                            Id = new Guid("0fcd8d02-609b-4afc-8f41-2fe5653c09d1"),
                            AdjustmentTypeName = "Abnormal",
                            Description = "",
                            Sign = 0
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdjustmentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("AdjustmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmountRecover")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferId");

                    b.ToTable("StockTransferItem");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc1a41cb-ac8e-4cd3-942d-0224253e333a"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("090cd748-7832-4149-9a69-6cc9683d5fdc"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("4a048301-32c4-4107-9889-74826d1fc3b6"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Televisions"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowDecimal")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cfa179f-aef3-490d-871f-c868a85aa32d"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("811ec4f9-23d2-4ba1-88ea-3af0a5a2e5fa"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("21fe0b5e-c885-49d2-9e93-d7d2456d05b7"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Piece"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionCount")
                        .HasColumnType("int");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageVisited")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11739037-7797-4f8e-b1d2-41ed2dfd7e4c"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "1 Year"
                        },
                        new
                        {
                            Id = new Guid("267ec9ab-5405-4fda-a988-513131166334"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("e65d4f83-cf7d-422d-a9a5-78caa56a0eb5"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "3 Years"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.ApplicableTax", "ApplicableTax")
                        .WithMany()
                        .HasForeignKey("ApplicableTaxId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BarcodeType", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SellingPriceTax", "SellingPriceTax")
                        .WithMany()
                        .HasForeignKey("SellingPriceTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SubCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicableTax");

                    b.Navigation("BarcodeType");

                    b.Navigation("Brand");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Category");

                    b.Navigation("ProductType");

                    b.Navigation("SellingPriceTax");

                    b.Navigation("Subcategory");

                    b.Navigation("Unit");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", "AdjustmentType")
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustmentType");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransferItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", "StockTransfer")
                        .WithMany("StockTransferItems")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockTransfer");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", b =>
                {
                    b.Navigation("StockTransferItems");
                });
#pragma warning restore 612, 618
        }
    }
}
