// <auto-generated />
using System;
using DevSkill.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSkill.Inventory.Web.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicableTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ApplicableTaxs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c131bf40-058a-4c00-a68b-bf13d8fbf907"),
                            ApplicableTaxName = "Food",
                            Description = "",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("203e2e10-8b9d-4109-870b-e8cb781ea1be"),
                            ApplicableTaxName = "Sales Tax",
                            Description = "",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("c8498195-b188-43b3-add3-7f4c9e9b2d7a"),
                            ApplicableTaxName = "Fruits",
                            Description = "",
                            TaxRate = 0m
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BarcodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarcodeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BarcodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dcbdbe1-183d-4828-83c9-273871ce3d7d"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "QR Code"
                        },
                        new
                        {
                            Id = new Guid("6cdf39af-3d83-4ef3-8b02-ae6c64a6f523"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "UPC"
                        },
                        new
                        {
                            Id = new Guid("c65ed4ea-6ea2-4efb-b1c7-e67a7ab5d070"),
                            BarcodeDescription = "",
                            BarcodeTypeCode = "",
                            BarcodeTypeName = "NFC"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74b9a5ef-d2f3-4539-984c-100fd5091a8c"),
                            BandOrigin = "",
                            BrandName = "Apple",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("c752f202-3076-4931-927b-d1427d8a28d5"),
                            BandOrigin = "",
                            BrandName = "Samsung",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("02e880eb-2788-452f-9e8a-43e6060c5ab3"),
                            BandOrigin = "",
                            BrandName = "Sony",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessLocations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e074ecc-ce90-49e4-98ae-d8bfaefe2169"),
                            Address = "",
                            City = "",
                            Country = "",
                            IsActive = true,
                            LocationName = "Warehouse A",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("d5a51edf-3bf8-48ac-8c84-6bb11d678fe6"),
                            Address = "",
                            City = "",
                            Country = "",
                            IsActive = true,
                            LocationName = "Warehouse B",
                            State = "",
                            ZipCode = ""
                        },
                        new
                        {
                            Id = new Guid("31949655-046e-420e-9da4-56885861fd98"),
                            Address = "",
                            City = "",
                            Country = "",
                            IsActive = true,
                            LocationName = "Downtown Store",
                            State = "",
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c7ef205-b37f-44c8-9e52-89516cd4a679"),
                            CategoryCode = "",
                            CategoryName = "Electronics",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("0527ecad-9a84-4433-8b03-9b68f78d7791"),
                            CategoryCode = "",
                            CategoryName = "Home Appliances",
                            Description = ""
                        },
                        new
                        {
                            Id = new Guid("9c20e045-e9c7-4aee-b1db-b10f07ad0265"),
                            CategoryCode = "",
                            CategoryName = "Clothing",
                            Description = ""
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertQuantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApplicableTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarcodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExciseTax")
                        .HasColumnType("float");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InclusiveTax")
                        .HasColumnType("float");

                    b.Property<double>("MarginTax")
                        .HasColumnType("float");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<int>("ReservedStock")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("SellingPriceTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StoreTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WarrantyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicableTaxId");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellingPriceTaxId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d80ecc1c-9053-4f44-bdc6-85b09ea1a87e"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("2640a352-5cb5-4668-b84a-d46b38c2ab78"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("e7e5f2f7-da8c-4f4f-8e39-48faac11281e"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Food"
                        },
                        new
                        {
                            Id = new Guid("c555db2a-fbcd-45dc-a89a-c189092dbc44"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("88db5d0b-6c3f-4420-86d9-aef564ff18ac"),
                            Description = "",
                            ProductTypeCode = "",
                            ProductTypeName = "Toys"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CurrentOutstanding")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("CustomerName");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProformaInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("DeliveryNo")
                        .IsUnique();

                    b.HasIndex("ProformaInvoiceId");

                    b.HasIndex("CustomerId", "DeliveryDate");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.DeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DeliveredQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("DeliveryId", "ProductId")
                        .IsUnique();

                    b.ToTable("DeliveryItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.DiscountRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CustomerType")
                        .HasColumnType("int");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Scope", "IsActive", "EffectiveFrom");

                    b.ToTable("DiscountRules");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.PaymentTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DueDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TermName")
                        .IsUnique();

                    b.ToTable("PaymentTerms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a1f0b2c-0001-4a1e-9f01-2b7d5c9e1001"),
                            Description = "Full payment is collected when the goods are handed over.",
                            DueDays = 0,
                            IsActive = true,
                            TermName = "Cash on Delivery"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0002-4a1e-9f01-2b7d5c9e1002"),
                            Description = "Full payment is received before the goods are released.",
                            DueDays = 0,
                            IsActive = true,
                            TermName = "Advance Payment"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0003-4a1e-9f01-2b7d5c9e1003"),
                            Description = "Half of the amount is paid up front and the rest on delivery.",
                            DueDays = 0,
                            IsActive = true,
                            TermName = "50% Advance, 50% on Delivery"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0004-4a1e-9f01-2b7d5c9e1004"),
                            Description = "Payment is due within 7 days of the invoice date.",
                            DueDays = 7,
                            IsActive = true,
                            TermName = "Net 7"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0005-4a1e-9f01-2b7d5c9e1005"),
                            Description = "Payment is due within 15 days of the invoice date.",
                            DueDays = 15,
                            IsActive = true,
                            TermName = "Net 15"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0006-4a1e-9f01-2b7d5c9e1006"),
                            Description = "Payment is due within 30 days of the invoice date.",
                            DueDays = 30,
                            IsActive = true,
                            TermName = "Net 30"
                        },
                        new
                        {
                            Id = new Guid("6a1f0b2c-0007-4a1e-9f01-2b7d5c9e1007"),
                            Description = "Payment is due within 60 days of the invoice date.",
                            DueDays = 60,
                            IsActive = true,
                            TermName = "Net 60"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PriceListName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PriceListName")
                        .IsUnique();

                    b.HasIndex("CustomerType", "IsActive", "EffectiveFrom");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.PriceListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MinQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PriceListId", "ProductId", "MinQuantity")
                        .IsUnique();

                    b.ToTable("PriceListItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ItemDiscountTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("OrderDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("PaymentTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProformaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProformaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SalespersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SalespersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("PaymentTermId");

                    b.HasIndex("ProformaNo")
                        .IsUnique();

                    b.HasIndex("CustomerId", "ProformaDate");

                    b.ToTable("ProformaInvoices");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProformaInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProformaInvoiceId");

                    b.ToTable("ProformaInvoiceItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SellingPriceTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellingPriceTaxName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SellingPriceTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b22d9b11-097d-44ea-8143-15adfefd8775"),
                            Description = "",
                            SellingPriceTaxName = "Exclusive",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("7e2b4ca2-3531-4ba0-bbb7-e6a36c224be2"),
                            Description = "",
                            SellingPriceTaxName = "Inclusive",
                            TaxRate = 0m
                        },
                        new
                        {
                            Id = new Guid("434581e0-22ab-42a4-81f3-cedf3854531a"),
                            Description = "",
                            SellingPriceTaxName = "Zero Rate",
                            TaxRate = 0m
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjustmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sign")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdjustmentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cefc62d6-036b-4a82-91d5-56190b73fe90"),
                            AdjustmentTypeName = "Normal",
                            Description = "",
                            Sign = 0
                        },
                        new
                        {
                            Id = new Guid("81a4a276-5a50-45b4-a989-87c60e2355d5"),
                            AdjustmentTypeName = "Abnormal",
                            Description = "",
                            Sign = 0
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AdjustmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmountRecover")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("BusinessLocationId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustmentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StockAdjustmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockAdjustmentId");

                    b.ToTable("StockAdjustmentItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StockTransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferId");

                    b.ToTable("StockTransferItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1058bef-e8d3-4820-9cd9-277dc02459e7"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("97331e14-0134-47c4-b7dc-7db73ebd6dca"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("bdd1fdb9-8385-4bff-bf69-5c6eade7765b"),
                            CategoryCode = "",
                            Description = "",
                            SubCategoryName = "Televisions"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowDecimal")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df3165eb-1d90-4ef0-8960-bb5e00b5ddae"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = new Guid("16772479-531a-4fa7-b93e-7d3409620906"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Liter"
                        },
                        new
                        {
                            Id = new Guid("81e63006-a7f1-4dd7-968e-5da6538ac01f"),
                            AllowDecimal = 0,
                            ShortName = "",
                            UnitName = "Piece"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionCount")
                        .HasColumnType("int");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageVisited")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.UserActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserActivityLogs");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c22e21a-d313-40fb-8ce8-70b09b204e1a"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "1 Year"
                        },
                        new
                        {
                            Id = new Guid("52d8f437-e62e-4cdf-bb04-b1e319fabb8c"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("d8137a0e-dfa8-4627-9c32-aa0203116f36"),
                            Description = "",
                            Name = "",
                            WarrantyDuration = "3 Years"
                        });
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.Product", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.ApplicableTax", "ApplicableTax")
                        .WithMany()
                        .HasForeignKey("ApplicableTaxId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BarcodeType", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SellingPriceTax", "SellingPriceTax")
                        .WithMany()
                        .HasForeignKey("SellingPriceTaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SubCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicableTax");

                    b.Navigation("BarcodeType");

                    b.Navigation("Brand");

                    b.Navigation("BusinessLocation");

                    b.Navigation("Category");

                    b.Navigation("ProductType");

                    b.Navigation("SellingPriceTax");

                    b.Navigation("Subcategory");

                    b.Navigation("Unit");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.Delivery", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoice", "ProformaInvoice")
                        .WithMany()
                        .HasForeignKey("ProformaInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessLocation");

                    b.Navigation("Customer");

                    b.Navigation("ProformaInvoice");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.DeliveryItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.Delivery", "Delivery")
                        .WithMany("DeliveryItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.DiscountRule", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.PriceListItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.PriceList", "PriceList")
                        .WithMany("PriceListItems")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoice", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.PaymentTerm", "PaymentTerm")
                        .WithMany()
                        .HasForeignKey("PaymentTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessLocation");

                    b.Navigation("Customer");

                    b.Navigation("PaymentTerm");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoiceItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoice", "ProformaInvoice")
                        .WithMany("ProformaInvoiceItems")
                        .HasForeignKey("ProformaInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProformaInvoice");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.AdjustmentType", "AdjustmentType")
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdjustmentType");

                    b.Navigation("BusinessLocation");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustmentItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", "StockAdjustment")
                        .WithMany("StockAdjustmentItems")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockAdjustment");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "FromWarehouse")
                        .WithMany()
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.BusinessLocation", "ToWarehouse")
                        .WithMany()
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransferItem", b =>
                {
                    b.HasOne("DevSkill.Inventory.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", "StockTransfer")
                        .WithMany("StockTransferItems")
                        .HasForeignKey("StockTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockTransfer");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.Delivery", b =>
                {
                    b.Navigation("DeliveryItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.PriceList", b =>
                {
                    b.Navigation("PriceListItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.SalesEntities.ProformaInvoice", b =>
                {
                    b.Navigation("ProformaInvoiceItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockAdjustmentEntites.StockAdjustment", b =>
                {
                    b.Navigation("StockAdjustmentItems");
                });

            modelBuilder.Entity("DevSkill.Inventory.Domain.Entities.StockTransferEntities.StockTransfer", b =>
                {
                    b.Navigation("StockTransferItems");
                });
#pragma warning restore 612, 618
        }
    }
}
