version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: DevSkill.Inventory.Web/Dockerfile
        image: inventory-image
        env_file: 
            - web.env
        ports:
            - "8080:80"
        entrypoint: ["dotnet", "DevSkill.Inventory.Web.dll"]
