version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: DevSkill.Inventory.Web/Dockerfile
        image: devskill-inventory
        env_file: 
            - web.env
        volumes:
            - ./Logs/Web:/app/Logs
        ports:
            - "8080:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        entrypoint: ["dotnet", "DevSkill.Inventory.Web.dll"]
volumes:
    inventory-data:
        external: true